name: Devpass checks

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Download test file
        run: curl -0 https://devpass-api-bucket.s3.amazonaws.com/testes/evercodeinc/challenge-1698259550887/divideNumbers.test.js -o divideNumbers.test.js

      - name: Run unit tests
        run: yarn test
